name: Detect & tag release

on:
  # on push to `main` but only if the version file changed
  push:
    branches: [ main ]
    paths:
      - 'spectrum.opam'
  workflow_dispatch:

jobs:
  tag-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          # fix for https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/2
          persist-credentials: false

      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x

      - id: version
        run: echo "::set-output name=version::$(opam info -f version .)"

      - name: Push version git tag
        uses: julb/action-manage-tag@v1
        with:
          name: ${{ steps.version.outputs.version }}
          state: present
        env:
          # use a PAT here rather than default `GITHUB_TOKEN` so that Actions are triggered after push
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
